apiVersion: v1
kind: Service
metadata:
  name: autoletics-app-service
spec:
  selector:
    app: autoletics-app
  ports:
    - port: 80
      targetPort: app-port
      protocol: TCP
  type: LoadBalancer
