apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autonomis
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "{{.Values.api_server}}"
    targetRevision: HEAD
    path: charts/autonomis-charts
  project: default
