apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autonomis
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/vampconnoisseur/autonomis-charts
    targetRevision: HEAD
    path: charts/autonomis-charts
  project: default
